name: Build And Deploy
on: [push]
permissions:
  contents: write
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          # channel: stable
          flutter-version-file: pubspec.yaml
      # - run: flutter --version
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle
      - uses: actions/upload-artifact@v4
        with:
          name: app-release-${{ github.sha }}.aab
          path: build/app/outputs/bundle/release/app-release.aab
      - uses: actions/upload-artifact@v4
        with:
          name: app-release-${{ github.sha }}.apk
          path: build/app/outputs/flutter-apk/app-release.apk
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          # channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build ios --release --no-codesign
      - uses: actions/upload-artifact@v4
        with:
          name: Runner-${{ github.sha }}.app
          path: build/ios/iphoneos/Runner.app
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          # channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build web --release --base-href /${{ github.event.repository.name }}/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
